### ISSUE TITLE
Add topics to repository

### ISSUE THREAD

**Issue by mendel5** [do-it-ger/Doit.Comdirect.Rest.Api#5]
Hi, can you add the following topic to this repository?
* https://github.com/topics/comdirect

Thanks!

**Comment by do-it-ger** [comment]
Sure :-)

@mendel5 Are you in charge for comdirect API?

**Comment by mendel5** [comment]
Thanks!

> Are you in charge for comdirect API?

No, I don't work for Comdirect...
